### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by monojk** [SYSPROG-JLS/S370BALEmulator#3]
Here's the error message:
```
Traceback (most recent call last):
File "C:\Users\jkein\Meine Ablage\IBMHistory\S370-125\DOSVS\S370BAL\S370BALEmulator.py", line 2570, in <module>
program_counter = mach_inst[_OC][1]()
File "C:\Users\jkein\Meine Ablage\IBMHistory\S370-125\DOSVS\S370BAL\S370BALEmulator.py", line 2049, in STH
Store_code(2)
File "C:\Users\jkein\Meine Ablage\IBMHistory\S370-125\DOSVS\S370BAL\S370BALEmulator.py", line 389, in Store_code
instrdata_list[dest + i] = op1[j:j+2]
IndexError: list assignment index out of range 
```
Here's the code:
```
         PRINT NOGEN
MANDEL   CSECT
         BALR  12,0
         USING *,12
*
         L     4,NROWS          Number of rows
*
FILLLOOP DS    0H
         L     3,=A(PRTOUT)     Load address of PRTOUT into register 3
         LTR   4,4              Check if all rows processed
         BZ    ENDLOOP          If zero, end loop
*
         LR    11,4             current row
         S     11,YOFFSET       subtract so that 0 is in the middle
         SLA   11,12            norm, R11 for division
         SR    10,10            clear R10
         D     10,DIVY          divide, quotient in R11
         ST    11,CIMAG
*         
         L     6,NCOLS          Number of columns
COLLOOP  DS    0H
         LTR   6,6              Check if all columns processed
         BZ    NEXTROW          If zero, go to next row
*
         LR    11,6             current column
         S     11,XOFFSET       subtract, so that 0 is in the middle
         SLA   11,12            norm, R11 for division
         SR    10,10            clear R10
         D     10,DIVX          divide, quotient in R11
         SR    10,10            clear R10
         SR    10,11            switch sign of R11, result in R10
*         L     10,CRTST
         ST    10,CREAL
*         
         LA    13,SAVEAREA
*         CALL  MANDELB,(PARAMLST) Call Mandelbrot function, /w params
         LA    1,PARAMLST       
*
         MVC   0(1,3),ANSWER    Store ANSWER character in PRTOUT
         LA    3,1(3)           Increment PRTOUT address
         BCT   6,COLLOOP        Decrement column counter and loop
*
NEXTROW  DS    0H
         BCT   4,FILLLOOP       Decrement row counter and loop
*
ENDLOOP  DS    0H
EXIT     EQU   *
*
         LTORG
SHIFT    EQU   12               norm  by 2**SHIFT         
CRASH    DC    D'0'             force crash
*
NCOLS    DC    F'100'           X  X: -5 ... 3
XOFFSET  DC    F'30'
DIVX     DC    F'30'
*
NROWS    DC    F'50'            Y  Y: -3 ... 3
YOFFSET  DC    F'25'
DIVY     DC    F'20'
*
CRTST    DC    F'1365'
CITST    DC    F'2048'
*
         DS    0D
         DC    CL4'PARA'         
CREAL    DC    F'0'             Real part of C 
CIMAG    DC    F'0'             Imaginary part of C
ANSWER   DC    C' ' 
*
PARAMLST DC    A(CREAL)
         DC    A(CIMAG)
         DC    A(ANSWER)
         DS    0D
SAVEAREA DS    18F'0'           Save Area
PRTOUT   DC    CL101' '         printer PRTOUT
*
         END   MANDEL         
```

**Comment by SYSPROG-JLS** [comment]
Hi monojk

This error in the emulator was caused by an error in the way adcons are created in the assembler (S370BALAsm). If you change 'L     3,=A(PRTOUT)' to 'LA    3,PRTOUT' then reassemble then try running the emluator you should find that this works. p.s. I also noticed in your code that you don't have a 'BR     14' after your label 'EXIT'. A 'BR    14' as the last instruction is a requirement of the emulator.

I will work on cleaning up adcon processing in S370BALAsm but this work-around should get you going again.

Regards,
Jim S

**Comment by SYSPROG-JLS** [comment]
Fixed Adcon processing in S370BALAsm.

Also added a trace facility to S370BALEmulator. To invoke this feature add -trace to the command line. The output from the trace will appear in 'OUTPUT.txt'

**Comment by monojk** [comment]
Thanks for the hint and the fix. For me to debug the outer and inner loops it would be useful to have a breakpoint stop if a certain register gets a certain value. Do you think that this is doable?

**Comment by monojk** [comment]
I managed to find my error by leducung the loops and stepping through. I did not use the SRDA opcode to propagate the negative sign before division, but simply cleared the even register. I did not know of this specialty. With SRDA my code works now as expected.
